version: '3.8'

services:
  mongo:
    image: mongo
    container_name: users-api-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: users-api-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
      - /app/node_modules
    command: node dist/main 

volumes:
  mongo_data:
